name: CI

on:
  push:
    branches: ["develop"]

permissions:
  id-token: write
  contents: read

jobs:
  build-api:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: dotnet build
        run: dotnet build ./api/src/DEXRPG/DEXRPG.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./api/src/DEXRPG/DEXRPG.WebApi/DEXRPG.WebApi.csproj --configuration Release -o artifacts

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dexrpg-api-artifact
          path: artifacts/

  deploy_dev_api:
    name: deploy dev
    needs: build-api
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev
      resource_group_name: dexrpg-rg
      app_service_name: dexrpg-web-api
      artifact_name: dexrpg-api-artifact
    secrets: inherit

  build-frontend:
    name: CI
    runs-on: ubuntu-latest
    needs: [build-api, deploy_dev_api]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 23.5.x
        uses: actions/setup-node@v2
        with:
          node-version: "23.5.x"
          cache: "pnpm"
          cache-dependency-path: "./web/WebApp/pnpm-lock.yaml"
      - name: Install dependencies
        working-directory: ./web/WebApp
        run: pnpm install
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dexrpg-app-artifact
          path: artifacts/
  deploy_dev_app:
    name: deploy dev
    needs: build-frontend
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev
      resource_group_name: dexrpg-rg
      app_service_name: dexrpg-web-app
      artifact_name: dexrpg-app-artifact
    secrets: inherit
