name: Pull Request

on:
  pull_request:
    branches: ["develop"]

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: dotnet restore
        run: dotnet restore ./api/src/DEXRPG/DEXRPG.sln --configuration Release

      - name: dotnet build
        run: dotnet build ./api/src/DEXRPG/DEXRPG.sln --configuration Release
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: build-api

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 23.5.x
        uses: actions/setup-node@v2
        with:
          node-version: "23.5.x"
          cache: "pnpm"
          cache-dependency-path: "./web/WebApp/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefix ./web/WebApp
      - name: Build pnpm
        run: pnpm build
        working-directory: ./web/WebApp
