name: "step - deploy"
on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      env:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string
      app_service_name:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy:
    name: deploy ${{inputs.app_service_name}} ${{inputs.env}}
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact_name}}
          path: artifacts/

      - name: "azure login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "deploy to azure app service"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{inputs.app_service_name}}-${{inputs.env}}
          package: artifacts/
